function file_save(arg0)
{
    GMBINWriteString(arg0, "GSWX:" + global.version);
    GMBINWriteString(arg0, global.route);
    GMBINWriteByte(arg0, global.level);
    GMBINWriteFloat(arg0, global.stage_num);
    GMBINWriteString(arg0, global.stage_ID);
    GMBINWriteShort(arg0, global.tot_turns);
    GMBINWriteInt(arg0, global.tot_points);
    GMBINWriteShort(arg0, global.tot_WP);
    GMBINWriteDouble(arg0, date_current_datetime());
    GMBINWriteDouble(arg0, global.sec);
    GMBINWriteByte(arg0, global.is_NG0);
    GMBINWriteByte(arg0, global.is_lvchg);
    GMBINWriteByte(arg0, global.GSP);
    GMBINWriteByte(arg0, global.GSP_max);
    GMBINWriteByte(arg0, global.num_defeat);
    GMBINWriteByte(arg0, global.is_IM_ini);
    GMBINWriteString(arg0, global.bgm_default);
    GMBINWriteString(arg0, global.team_name);
    GMBINWriteInt(arg0, global.c_tot_points);
    GMBINWriteInt(arg0, global.c_tot_WP);
    GMBINWriteDouble(arg0, global.c_tot_sec);
    GMBINWriteInt(arg0, global.c_atk_dam);
    GMBINWriteInt(arg0, global.c_hit_dam);
    GMBINWriteString(arg0, global.c_atk_data);
    GMBINWriteString(arg0, global.c_hit_data);
    GMBINWriteShort(arg0, global.c_Oimo);
    GMBINWriteShort(arg0, global.c_Photo);
    GMBINWriteShort(arg0, global.c_Yume);
    GMBINWriteShort(arg0, global.c_Toyohime);
    GMBINWriteShort(arg0, global.c_Makura);
    GMBINWriteShort(arg0, global.c_Meko);
    GMBINWriteByte(arg0, global.c_Akyu);
    GMBINWriteByte(arg0, global.c_Lily);
    GMBINWriteByte(arg0, global.is_NG1);
    ds_list_write_ext(arg0, global.p_list, 0);
    ds_list_write_ext(arg0, global.p_name_id, 2);
    ds_list_write_ext(arg0, global.p_name_name, 8);
    ds_list_write_ext(arg0, global.p_hist, 8);
    ds_grid_write_ext(arg0, global.pairs, 0);
    ds_list_write_ext(arg0, global.d_pair, 0);
    ds_list_write_ext(arg0, global.l_select, 0);
    ds_list_write_ext(arg0, global.l_BGM, 8);
    ds_grid_write_ext(arg0, global.tune_lv, 0);
    ds_grid_write_ext(arg0, global.char_lv, 0);
    ds_grid_write_ext(arg0, global.skill_id, 8);
    ds_grid_write_ext(arg0, global.skill_lv, 0);
    ds_grid_write_ext(arg0, global.item_id, 8);
    ds_list_write_ext(arg0, global.u_code, 8);
    ds_list_write_ext(arg0, global.u_data, 8);
    ds_list_write_ext(arg0, global.BGM, 8);
    ds_list_write_ext(arg0, global.rem_HP, 2);
    ds_list_write_ext(arg0, global.rem_MP, 2);
    ds_list_write_ext(arg0, global.rem_BL, 8);
    ds_list_write_ext(arg0, global.tbonus, 0);
    ds_list_write_ext(arg0, global.p_code, 8);
    ds_list_write_ext(arg0, global.p_data, 8);
    ds_list_write_ext(arg0, global.EXP, 2);
    ds_list_write_ext(arg0, global.PP, 4);
    ds_list_write_ext(arg0, global.tot_PP, 4);
    ds_list_write_ext(arg0, global.geki, 2);
    ds_list_write_ext(arg0, global.WP, 2);
    ds_list_write_ext(arg0, global.skill_aq, 8);
    ds_list_write_ext(arg0, global.rem_SP, 2);
    ds_list_write_ext(arg0, global.rem_PW, 0);
    ds_list_write_ext(arg0, global.wbonus, 0);
    ds_list_write_ext(arg0, global.trust, 8);
    ds_list_write_ext(arg0, global.updates_ID, 0);
    ds_list_write_ext(arg0, global.updates_char, 8);
    ds_list_write_ext(arg0, global.updates_val, 8);
    ds_list_write_ext(arg0, global.u_code0, 8);
    ds_list_write_ext(arg0, global.u_data0, 8);
    ds_list_write_ext(arg0, global.p_code0, 8);
    ds_list_write_ext(arg0, global.p_data0, 8);
    ds_list_write_ext(arg0, global.PP0, 4);
    ds_list_write_ext(arg0, global.geki0, 2);
    ds_list_write_ext(arg0, global.item0, 0);
    ds_list_write_ext(arg0, global.c_st_stage, 0);
    ds_list_write_ext(arg0, global.c_st_level, 0);
    ds_list_write_ext(arg0, global.c_st_turns, 2);
    ds_list_write_ext(arg0, global.c_st_time, 4);
    ds_list_write_ext(arg0, global.c_st_beat, 2);
    ds_list_write_ext(arg0, global.c_st_enemies, 2);
    ds_list_write_ext(arg0, global.c_st_beaten, 0);
    ds_list_write_ext(arg0, global.c_st_points, 4);
    ds_list_write_ext(arg0, global.c_st_spell0, 0);
    ds_list_write_ext(arg0, global.c_st_spell1, 0);
    ds_list_write_ext(arg0, global.c_st_bonus, 0);
    ds_list_write_ext(arg0, global.c_st_defeat, 2);
    ds_list_write_ext(arg0, global.c_st_save, 2);
    ds_list_write_ext(arg0, global.c_st_load, 2);
    ds_list_write_ext(arg0, ObjData.ItemID, 8);
    ds_list_write_ext(arg0, global.tot_num_of_items, 0);
    ds_list_write_ext(arg0, global.num_of_items, 0);
    ds_list_write_ext(arg0, ObjData.FlagID, 8);
    ds_list_write_ext(arg0, ObjData.FlagIsOn, 0);
}
